version: "2.2"

services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    mem_limit: ${MEM_LIMIT}
    networks:
      - es-net
    ports:
      - ${ES_PORT}:${ES_PORT}

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - ${KIBANA_PORT}:${KIBANA_PORT}

networks:
  es-net:
    driver: bridge